/*
This test file for helpers is generated by IntelliJ Ultimate,
therefore expect it to possibly have low quality test.
*/
package helpers

import "testing"

func TestPrintExpected(t *testing.T) {
	type args struct {
		expected any
	}
	tests := []struct {
		name string
		args args
	}{
		// TODO: Add test cases.
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			PrintExpected(tt.args.expected)
		})
	}
}

func TestPrintGotFatalError(t *testing.T) {
	type args struct {
		test   *testing.T
		result any
	}
	tests := []struct {
		name string
		args args
	}{
		// TODO: Add test cases.
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			PrintGotFatalError(tt.args.test, tt.args.result)
		})
	}
}

func TestPrintNotExpected(t *testing.T) {
	type args struct {
		test     *testing.T
		result   any
		expected any
	}
	tests := []struct {
		name string
		args args
	}{
		// TODO: Add test cases.
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			PrintNotExpected(tt.args.test, tt.args.result, tt.args.expected)
		})
	}
}

func TestResultIsExpected(t *testing.T) {
	type args struct {
		result   any
		expected any
	}
	tests := []struct {
		name string
		args args
		want bool
	}{
		// TODO: Add test cases.
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if got := ResultIsExpected(tt.args.result, tt.args.expected); got != tt.want {
				t.Errorf("ResultIsExpected() = %v, want %v", got, tt.want)
			}
		})
	}
}

func TestStandardTestChecking(t *testing.T) {
	type args struct {
		test     *testing.T
		result   any
		expected any
	}
	tests := []struct {
		name string
		args args
	}{
		// TODO: Add test cases.
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			StandardTestChecking(tt.args.test, tt.args.result, tt.args.expected)
		})
	}
}
